# Generated by Django 6.0.4 on 2026-04-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
