# Generated by Django 6.0.4 on 2026-04-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
