# Generated by Django 6.0.4 on 2026-04-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_album_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='id_album',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='album_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.album'),
        ),
    ]
