# Generated by Django 6.0.4 on 2026-04-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_carrinho_id_album_carrinho_album_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='album_id',
            new_name='album',
        ),
    ]
