# Generated by Django 6.0.4 on 2026-04-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_album_id_carrinho_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artista_id',
            new_name='artista',
        ),
    ]
